#!/bin/sh

lpr_is_ifname() {
	value="${1:-}"
	case "$value" in
		''|*[!A-Za-z0-9_.:-]*)
			return 1
			;;
	esac
}

lpr_trim_line() {
	printf '%s' "${1:-}" | sed 's/^[	 ]*//; s/[	 ]*$//'
}

lpr_clean_domain() {
	line="${1:-}"
	line="${line%%#*}"
	line="$(lpr_trim_line "$line")"

	case "$line" in
		.*) line="${line#.}" ;;
	esac

	printf '%s\n' "$line"
}

lpr_dns_domain_lines() {
	file="$1"
	role="$2"
	backend="$3"
	dns_result="$4"
	proxy_dns="$5"

	case "$backend" in
		nftset|ipset) ;;
		*) return 1 ;;
	esac
	case "$role" in
		adblock|proxy|bypass) ;;
		*) return 1 ;;
	esac
	case "$dns_result" in
		real-ip|fake-ip|mixed) ;;
		*) return 1 ;;
	esac

	[ -f "$file" ] || return 0

	while IFS= read -r raw || [ -n "$raw" ]; do
		domain="$(lpr_clean_domain "$raw")"
		lpr_is_domain "$domain" || continue

		case "$role" in
			adblock)
				printf 'address=/%s/0.0.0.0\n' "$domain"
				;;
			proxy)
				printf 'server=/%s/%s\n' "$domain" "$proxy_dns"
				case "$backend" in
					nftset)
						printf 'nftset=/%s/4#inet#lan_proxy_route#proxy_v4\n' "$domain"
						;;
					ipset)
						printf 'ipset=/%s/lpr_proxy_v4\n' "$domain"
						;;
				esac
				if [ "$dns_result" = "fake-ip" ]; then
					printf '# fake-ip domain %s is expected to be restored by the X86 proxy\n' "$domain"
				fi
				;;
			bypass)
				printf '# bypass-domain %s\n' "$domain"
				;;
		esac
	done < "$file"
}

lpr_dnsmasq_render_config() {
	backend="$1"
	domestic_dns_csv="$2"
	proxy_dns="$3"
	shift 3

	case "$backend" in
		nftset|ipset) ;;
		*) return 1 ;;
	esac

	printf '# generated by lan-proxy-route\n'

	old_ifs="$IFS"
	IFS=,
	for dns in $domestic_dns_csv; do
		dns="$(lpr_trim_line "$dns")"
		[ -n "$dns" ] && printf 'server=%s\n' "$dns"
	done
	IFS="$old_ifs"

	while [ "$#" -gt 0 ]; do
		spec="$1"
		shift

		case "$spec" in
			*:*:*)
				file="${spec%%:*}"
				rest="${spec#*:}"
				role="${rest%%:*}"
				dns_result="${rest#*:}"
				;;
			*)
				[ "$#" -ge 2 ] || return 1
				file="$spec"
				role="$1"
				dns_result="$2"
				shift 2
				;;
		esac

		lpr_dns_domain_lines "$file" "$role" "$backend" "$dns_result" "$proxy_dns"
	done
}

lpr_dns_render_firewall() {
	backend="$1"
	lan_if="$2"
	router_ip="$3"
	hijack_53="$4"
	block_dot="$5"

	case "$backend" in
		nftset|ipset) ;;
		*) return 1 ;;
	esac
	lpr_is_ifname "$lan_if" || return 1
	lpr_is_ipv4 "$router_ip" || return 1
	case "$hijack_53" in
		0|1) ;;
		*) return 1 ;;
	esac
	case "$block_dot" in
		0|1) ;;
		*) return 1 ;;
	esac

	if [ "$backend" = "nftset" ] && { [ "$hijack_53" = "1" ] || [ "$block_dot" = "1" ]; }; then
		cat <<EOF
nft add chain inet $LPR_TABLE_NAME dns_hijack '{ type nat hook prerouting priority dstnat; policy accept; }'
EOF
	fi

	if [ "$hijack_53" = "1" ]; then
		case "$backend" in
			nftset)
				cat <<EOF
nft add rule inet $LPR_TABLE_NAME dns_hijack iifname "$lan_if" udp dport 53 redirect to :53
nft add rule inet $LPR_TABLE_NAME dns_hijack iifname "$lan_if" tcp dport 53 redirect to :53
EOF
				;;
			ipset)
				cat <<EOF
iptables -t nat -A PREROUTING -i $lan_if -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -i $lan_if -p tcp --dport 53 -j REDIRECT --to-ports 53
EOF
				;;
		esac
	fi

	if [ "$block_dot" = "1" ]; then
		case "$backend" in
			nftset)
				printf 'nft add rule inet %s dns_hijack iifname "%s" tcp dport 853 reject\n' "$LPR_TABLE_NAME" "$lan_if"
				;;
			ipset)
				printf 'iptables -A FORWARD -i %s -p tcp --dport 853 -j REJECT\n' "$lan_if"
				;;
		esac
	fi
}
